# Generated by Django 3.0.8 on 2020-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_customer_driver_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
